api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /


admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc